/* =========================================================================
   English interface strings.
   Namespaced per tool -- numbers-to-words.html's dictionary is extracted
   here verbatim; trade-finance-reference.html's is added as a sibling
   namespace when that page is migrated next, so the two tools' keys never
   collide (both have things like "labelSearch"-shaped concerns, and
   colliding on a shared flat object would be a real, not hypothetical,
   risk once a second tool lands here).
   ========================================================================= */
export const en = {
  numbersToWords: {
    appTitle: 'Numbers to Words Converter',
    skipToContent: 'Skip to main content',
    ariaCopyEnglish: 'Copy English amount in words',
    ariaCopyArabic: 'Copy Arabic amount in words',
    bulkTableCaption: 'Bulk conversion results, one row per line',
    ariaBulkTableScroll: 'Bulk conversion results table, scrollable horizontally',
    sectionInput: 'Amount Details',
    labelAmount: 'Amount',
    hintAmount: function (n) {
      return 'Thousands separators are inserted automatically. ' +
        (n === 0 ? 'This currency has no decimal places.' : 'Maximum ' + n + ' decimal place' + (n === 1 ? '' : 's') + ' for the selected currency.');
    },
    labelFilter: 'Find currency',
    labelCurrency: 'Currency',
    labelFormat: 'Output style',
    hintFormat: 'Financial: standard amount-in-words. Check: cheque-writing convention (English only). Standard: plain number, no currency.',
    formatStandard: 'Standard (plain number)',
    formatFinancial: 'Financial (amount-in-words)',
    formatCheck: 'Check / payment style',
    customTitle: 'Custom currency definition',
    customCode: 'ISO code', customGender: 'Arabic gender',
    customEnS: 'English singular', customEnP: 'English plural',
    customArS: 'Arabic singular', customArD: 'Arabic dual',
    customArP: 'Arabic plural', customArA: 'Arabic accusative',
    genderM: 'Masculine', genderF: 'Feminine',
    btnClear: 'Clear', btnCopy: 'Copy',
    btnCopyResult: 'Copy Amount in Words', btnCopyAll: 'Copy All',
    copied: 'Copied',
    btnPrint: 'Print',
    certificateTitle: 'Amount in Words Certificate',
    certificateFooter: 'Generated by Numbers to Words Converter',
    certificateMeta: function (currency, dateStr) { return currency + ' — Generated ' + dateStr; },
    sectionResult: 'Conversion Result',
    labelNumeric: 'Numeric Amount',
    labelWordsEn: 'Amount in Words — English',
    labelWordsAr: 'Amount in Words — Arabic',
    footerBuilt: 'Built by Abdulrahman Alzahrani',
    customOption: 'CUSTOM — Custom currency',
    sectionBulk: 'Bulk Conversion',
    hintBulk: 'One amount per line. Uses the currency, output style, and language selected above.',
    labelBulk: 'Amounts',
    btnBulkConvert: 'Convert All',
    btnBulkCopy: 'Copy Results',
    btnBulkImportCsv: 'Import CSV',
    btnBulkExportCsv: 'Export CSV',
    hintBulkCsv: 'CSV import uses the first column, or a column named "Amount" if present.',
    bulkPlaceholder: '1000\n2500.50\n10000',
    bulkColLine: 'Line', bulkColAmount: 'Amount', bulkColNumeric: 'Numeric', bulkColWords: 'Amount in Words',
    bulkEmpty: 'Enter one amount per line, then click Convert All.',
    bulkSummary: function (ok, err) {
      return ok + ' converted' + (err ? ', ' + err + ' error' + (err === 1 ? '' : 's') : '');
    },
    bulkTruncated: function (max) { return 'Only the first ' + max + ' lines were converted; the rest were ignored.'; },
    bulkCsvImported: function (n) { return 'Imported ' + n + ' amount' + (n === 1 ? '' : 's') + ' from the CSV file.'; },
    bulkCsvEmpty: 'No amounts were found in that CSV file.',
    bulkCsvReadError: 'Could not read that file. Please choose a CSV file.',
    bulkNoResults: 'Convert All first — there are no results yet.',
    bulkReportTitle: 'Bulk Conversion Report',
    bulkReportMeta: function (currency, dateStr) { return currency + ' — Generated ' + dateStr; },
    err: {
      EMPTY: 'Please enter an amount.',
      NO_DIGITS: 'Please enter a valid numeric amount.',
      INVALID_CHARS: 'Invalid characters. Use digits, commas as thousands separators, and a single period for decimals.',
      MULTIPLE_DECIMALS: 'More than one decimal point was entered. Use a single period, for example 123,456.78.',
      BAD_COMMAS: 'Invalid comma placement. Thousands separators must group digits in threes, for example 1,250,000.00.',
      TOO_MANY_DECIMALS: function (n) {
        return 'Only ' + n + ' decimal place' + (n === 1 ? '' : 's') + ' ' + (n === 1 ? 'is' : 'are') +
          ' supported for the selected currency. The amount has not been rounded — please correct it.';
      },
      NEGATIVE: 'Negative amounts are not supported for financial documentation.',
      TOO_LARGE: 'The amount exceeds the supported range (maximum 36 whole-number digits).',
      CUSTOM_INCOMPLETE: 'Complete the custom currency: English singular name and all four Arabic forms (singular, dual, plural, accusative) are required. A missing Arabic dual, in particular, would drop the number "2" from the wording.'
    }
  },
  tradeFinanceReference: {
    appTitle: 'Trade Finance Reference',
    footerBuilt: 'Built by Abdulrahman Alzahrani',
    sectionSearch: 'Search',
    labelSearch: 'Ask a question or search a topic',
    hintSearch: 'Try an article number ("UCP 30", "Article 20"), a rule code ("FOB"), or a plain question ("who pays for insurance under CIF").',
    sectionResults: 'Results',
    emptyState: 'No matches. Try different words, or clear the search to browse everything.',
    sectionAbout: 'About this reference',
    chipAll: 'All',
    resultCount: function (n) { return n + (n === 1 ? ' result' : ' results'); },
    sectionMatrix: 'Incoterms® 2020 Responsibility Chart',
    matrixHint: 'Who pays for what, under each rule. Click a rule’s code to highlight its column. Scroll sideways on narrow screens.',
    matrixNote: 'This chart is an original compilation of publicly known Incoterms® 2020 cost/risk allocations, cross-checked against a secondary published reference. It is not affiliated with, and does not reproduce, any third party’s copyrighted chart design. Always verify against the official ICC Incoterms® 2020 publication.',
    matrixRuleHeader: 'Obligation \\ Rule',
    matrixLegend: 'Blue = buyer pays. Gray = seller pays. Amber = negotiable between the parties.',
    matrixTransferOfRisk: 'Transfer of risk',
    matrixFreightTerms: 'Freight terms',
    freightCollect: 'Freight collect',
    freightPrepaid: 'Freight prepaid',
    aboutBody: [
      'This tool provides original, plain-language summaries of Incoterms® 2020, ICC Uniform Customs and Practice for Documentary Credits (UCP 600), and ICC Uniform Rules for Demand Guarantees (URDG 758), plus a topic-level index of ICC International Standard Banking Practice (ISBP 821) — it does not reproduce ICC’s copyrighted rule text. It is offline, works entirely in your browser, and sends no data anywhere.',
      'These summaries are a study and orientation aid, not legal advice and not a substitute for the official ICC publications. Always verify the exact wording of the applicable rule against the current official ICC text before relying on it for a live transaction, guarantee, or letter of credit.'
    ]
  },
  landing: {
    appTitle: 'Number & Trade Finance Tools',
    footerBuilt: 'Built by Abdulrahman Alzahrani',
    skipToContent: 'Skip to main content',
    introTitle: 'Choose a Tool',
    introText: 'Two offline, bilingual tools for financial and trade documentation. Nothing you type is ever sent anywhere -- everything runs entirely in your browser.',
    ntwTitle: 'Numbers to Words Converter',
    ntwDesc: 'Convert amounts into formal English and Arabic words for financial documents, cheques, and contracts -- including bulk conversion, CSV import/export, and printable output.',
    tfrTitle: 'Trade Finance Reference',
    tfrDesc: 'A bilingual reference and search tool for Incoterms 2020, UCP 600, URDG 758, and an ISBP 821 topic index.',
    openTool: 'Open'
  }
};
